## 00 pytorch fundamentals

# https://www.learnpytorch.io/ 

# My Research: https://docs.google.com/document/d/19H92ZCM-CFy-sBSZDfoBPVHS8HZei0sU8QHyQJuFkvY/edit

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


# Intro to Tensors

# Creating tensors:

# All of these are tensors, but vectors and scalars are just denominated by their size

In [2]:
# Scalar
# torch.tensor() =  https://pytorch.org/docs/stable/tensors.html 
# magnitude

# creates datatype
scalar = torch.tensor(7)
# get tensor back as python int:
scalar.item()

# get dimensions:
# dimension = number of pairs of closing square brakets
scalar.ndim

0

In [3]:
# Vector
# magnitude and direction

vector = torch.tensor([7,7])
vector

vector.ndim

# Shape is just how many elements
vector.shape

torch.Size([2])

In [4]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])

MATRIX

MATRIX.ndim

# Indexes
MATRIX[0]

tensor([7, 8])

In [5]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,6]]])

#Dimensions = 3
#Shape = [1,3,3] based on how many things are inside each layer



# Random Tensor

# Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numebers

In [6]:
# create a random tensor of size

# https://pytorch.org/docs/stable/generated/torch.rand.html

random_tensor = torch.rand(3,4)
random_tensor2 = torch.rand(1,3,4)
random_tensor, random_tensor2

(tensor([[0.4588, 0.0150, 0.9819, 0.3628],
         [0.9700, 0.5863, 0.2425, 0.7947],
         [0.4919, 0.7303, 0.8951, 0.9758]]),
 tensor([[[0.3994, 0.6522, 0.9449, 0.6836],
          [0.2616, 0.1834, 0.3199, 0.7334],
          [0.7197, 0.9353, 0.7530, 0.6045]]]))

In [7]:
# Create a random tensor with similar shape to an image tensor

random_img_tensor = torch.rand(size=(244,244,3)) # height, width, color channels (rgb)
random_img_tensor

tensor([[[0.0435, 0.7544, 0.6295],
         [0.0396, 0.6035, 0.2980],
         [0.2493, 0.1132, 0.6001],
         ...,
         [0.8943, 0.2192, 0.3758],
         [0.8633, 0.5382, 0.3362],
         [0.6063, 0.9460, 0.9869]],

        [[0.1156, 0.6023, 0.1447],
         [0.4144, 0.5198, 0.5079],
         [0.0169, 0.5309, 0.6028],
         ...,
         [0.0585, 0.4561, 0.3869],
         [0.1895, 0.8744, 0.6591],
         [0.3183, 0.4270, 0.2564]],

        [[0.3934, 0.1386, 0.8484],
         [0.0561, 0.9865, 0.1488],
         [0.4337, 0.0206, 0.0063],
         ...,
         [0.5206, 0.9386, 0.5501],
         [0.7622, 0.9289, 0.6915],
         [0.6892, 0.5759, 0.9467]],

        ...,

        [[0.6391, 0.3412, 0.8263],
         [0.2973, 0.4656, 0.2184],
         [0.3120, 0.3078, 0.4245],
         ...,
         [0.2080, 0.8264, 0.4491],
         [0.6671, 0.1228, 0.9287],
         [0.3447, 0.7316, 0.3542]],

        [[0.9761, 0.0688, 0.2703],
         [0.2839, 0.9472, 0.9613],
         [0.

###Zeros and Ones

In [8]:
# create a tensor of all zeros 
zeros = torch.zeros(size=(3,4))
zeros

# can mulitply previous tensors to zero them out, ignores data but keeps shape

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

#ones.dtype

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
random_tensor.dtype

torch.float32

###Creating a range of tensors and tensor-like 

https://pytorch.org/docs/stable/generated/torch.arange.html

In [11]:
#usse torch.arange
oneto11 = torch.arange(start=0, end=1100, step = 77)
oneto11

tensor([   0,   77,  154,  231,  308,  385,  462,  539,  616,  693,  770,  847,
         924, 1001, 1078])

In [12]:
# Creating tensors like

tenzeros = torch.zeros_like(input= oneto11)
tenzeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor Datatypes 

one of the big 3 errors that you run into in deep learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device (must be same device and shape to operate on each other) 

In [13]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g float32 or float16 torch.float32) 32 contains 32 bits in memory
                               device=None, # what device your tensor is on
                               requires_grad=False) # whether or not to track gradients with this tensors operations

float_32_tensor

tensor([3., 6., 9.])

float has to do with precision in computing, meausre of the detail in which the quantity is expressed. less bits run faster, but have less precision

In [14]:
float_32_tensor.dtype

torch.float32

In [15]:
float16Tensor = float_32_tensor.type(torch.float16)
float16Tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [16]:
float16Tensor * float_32_tensor # works even though theyre different datatypes, sometimes it doesn't. 

tensor([ 9., 36., 81.])

In [17]:
int_32_T = torch.tensor([3,6,9],
                        dtype=torch.int32)

### RECAP: Getting info from tensors:

Check device (tensor.device),
datatype (tensor.dtype), 
and shape (tensor.shape)


***TENSOR ATTRIBUTE***

In [18]:
#create tensor
some_t = torch.rand(3,4)
some_t

tensor([[0.4614, 0.0690, 0.9966, 0.9996],
        [0.5593, 0.5461, 0.3499, 0.3386],
        [0.7609, 0.6837, 0.8208, 0.7066]])

In [19]:
# find out details
print(some_t)
print(f"Datatype of tensor: {some_t.dtype}")
print(f"Shape of tensor: {some_t.shape}")
print(f"Device tensor is on: {some_t.device}")

tensor([[0.4614, 0.0690, 0.9966, 0.9996],
        [0.5593, 0.5461, 0.3499, 0.3386],
        [0.7609, 0.6837, 0.8208, 0.7066]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


***MANIPULATING TENSORS***

#Tensor Operations

- Addition
- subtraction
- multiplication (element-wise)
- Division 
- Tensor multiplication

In [20]:
#Create Tensor and add 10
tdawg = torch.tensor([1,2,3])
tdawg + 10 


tensor([11, 12, 13])

In [21]:
#Multiply by 10
tdawg * 10


tensor([10, 20, 30])

In [22]:
# Subtract 10
tdawg - 10


tensor([-9, -8, -7])

In [23]:
# Try out pytorch inbuilt functions

torch.mul(tdawg, 10)
 

tensor([10, 20, 30])


# two main ways of multiplying in in deep learning and neural networks

1. Element Wise 
2. Matrix multiplication (dot product)

More info: https://www.mathsisfun.com/algebra/matrix-multiplying.html 

In [24]:
# Element-wise

print(tdawg, "*", tdawg)
print(f"Equals: {tdawg*tdawg}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [25]:
#Matrix Mult

torch.matmul(tdawg, tdawg)

tensor(14)

#matrix mult by hand
1*1 + 2x2 + 3x3 = 14

In [26]:
%%time 
value = 0
for i in range(len(tdawg)):
  value += tdawg[i] * tdawg[i]
print(value)


tensor(14)
CPU times: user 2.21 ms, sys: 0 ns, total: 2.21 ms
Wall time: 9.18 ms


#functions are optimized and faster

Useful visualization tool: http://matrixmultiplication.xyz/ 

#Rules that need to be satisfied for matrix multiplication:

# 1. inner dimensions must match:
- (3,2) @ (3,2) wont work
- (2,3) @ (3,2) will work
- (3,2) @ (2,3) will work 

2. The resulting matrix has the shape of the outer dimensions:
- (2,3) @ (3,2) -> (2,2)
- (3,2) @ (2,3) -> (3,3)

#one of the most common errors are shape errors





In [27]:
tensorAA = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensorBB = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
# torch.mm(tensorAA, tensorBB) alias for torch.matmul
torch.matmul(tensorAA, tensorBB)



RuntimeError: ignored

#To fix shape issues, we can manipulate the shape of our tensors using transpose

The transpose switches the axes or dimensions of a given tensor

In [ ]:
tensorAA = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensorBB = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
# torch.mm(tensorAA, tensorBB) alias for torch.matmul
#torch.matmul(tensorAA, tensorBB)
print(tensorAA, tensorAA.shape, f"tensorA")

print(f"tensorB")
print(tensorBB.shape)
print(tensorBB)

#.T transposes the tensor

print(tensorBB.T.shape)

print(tensorBB.T)

output = torch.matmul(tensorAA, tensorBB.T)
print(output)

#Finding the min, max, mean, sum, etc of tensor (Tensor aggregation)

In [ ]:
tensorC = torch.arange(0,100,10)
print(tensorC)
print(tensorC.dtype)

#find min
print(torch.min(tensorC))

#find max
print(torch.max(tensorC))

#find the mean // DOESNT WORK ON INT64
#Needs to be floating pount or complex dtype 
print(torch.mean(tensorC.type(torch.float32)))

#Finding Positional Min and Max

In [ ]:
#Find the position in tensor that has minimum value with argmin() -> return index position of target tensor where the minimum value occurs

In [ ]:
tensorC.argmin()

In [ ]:
tensorC.argmax()

## Reshaping, stacking, squeezing and unsqueezing tensors

* reshaping - reshapes input tensor to a defined shape
* view - return a view of an input tensor of a certain shape but keep the same memory as the original tensor 
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack) https://pytorch.org/docs/stable/generated/torch.stack.html 
* Squeeze - removes all 1 dimensions from a tensor
* unsqueeze - add a 1 dimension to a tensor
* permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
import torch
tensa = torch.arange(1., 13. )
tensa.shape, tensa


In [ ]:
# add extra dimension

#tensa_reshaped = tensa.reshape(1,7)

# ^ this will be invalid since the shape cannot be reshaped since it mathematically cannot work

#tensa_reshaped = tensa.reshape(9,1 )
#                              
tensa_reshaped2 = tensa.reshape(6,2)
print(tensa_reshaped2)

In [ ]:
b = torch.arange(1., 10. )
c = b.view(9,1)
c, b

In [ ]:
# stack tensors on top of eachother

b_stacked = torch.stack([b,b,b,b], dim=1)
b_stacked


In [ ]:
tensa_reshaped2.shape

In [ ]:
tensa_reshaped2.squeeze().shape

In [ ]:
# torch.squeeze() - removes all single dimensions from target tensor
tensor111 = torch.arange(1,13)
tensor11 = tensor111.reshape(1,12)
print(f"previous tensor: {tensor11}")
print(f"previous shape: {tensor11.shape}")

#remove extra dimensions from tensor11
squeezed11 = tensor11.squeeze()
print(f"new tensor: {squeezed11}")
print(f"previous shape: {squeezed11.shape}")

#Then torch.unsqueeze() to add dimension
newnew= squeezed11.unsqueeze(dim=1)
print("unsqueeze:", newnew, newnew.shape)





In [ ]:
#torch.permute - basically means rearange dimensions
xx = torch.rand(size = (224,224,3)) #height, width, color channels, image data standard

#permute original tensor to rearange the dimensions
xxx = xx.permute(2,0,1) # shifts dimensions 2 to 0, 0 to 1, and 1 to 2

print(f"previous shape: {xx.shape}")
print(f"new shape: {xxx.shape}")

## Indexing (selecting data from tensors)

#Similar to numpy

In [ ]:
import torch
s = torch.arange(1,10).reshape(1,3,3)
print(s)


In [ ]:
s[0]

In [ ]:
#index on middle bracket
#s[0,0] or s[0][0]
s[0][0]


In [ ]:
#middle most
s[0][0][0]

In [ ]:
# you can also use : to select all of a target dimensions
s[:, 0]

In [ ]:
# get all values of the 0th and  1st dimensions but only index 1 of the 2nd dimension
s[:,:, 1]

In [ ]:
# get all values of the 0 dimension but only the 1 index value of the 1st and 2nd 
s[ :, 1, 1]

In [ ]:
# get index 0 of 0th and 1st dimension and all values of second dimension
s[0,0,:]

In [ ]:
s[:,:,2]

In [ ]:
s[:, 2,2]


# Pytorch tensors & numpy

Pytorch has functionality to interact with numpy data
* data in numpy, want in torch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> numpy -> `torch.tensor.numpy()`

In [ ]:
# Numpy to tensor

import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) #warning: when converting from numpy -> pytorch, pytorch reflects numpy default datatype of float64 unless specefied otherwise
print(array, tensor)

In [ ]:
array.dtype

In [ ]:
torch.arange(1.0,8.0).dtype

In [ ]:
array = array + 1 # all added by 1

In [ ]:
tensor111 = torch.ones(7)
numpy_tensor = tensor111.numpy()
tensor111,numpy_tensor

##Reproducability (trying to take random out of random)

In short how a neural network learns:

Start with random numbers -> tensor operations -> update random numbers to try and make them  better representations of the data -> again -> again -> again.....

To reduce randomness in neural networks and PyTorch comes the concept of a random seed.

Essentially a random seed " flavors" the randomness

In [ ]:
import torch

#Two random tensors

randomA = torch.rand(3,4)
randomB = torch.rand(3,4)

print(randomA)
print(randomB)
print(randomA == randomB)

In [ ]:
# Lets make some random but reproducable tensors

import torch

#set random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
randomC = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
randomD = torch.rand(3,4)

print(randomC, '\n', randomD)

#Running tensors and PyTorch objects on GPUs (faster computation)

To get a gpu, collab has the function built in

Use your own - takes some set up

`torch.cuda.is_available()`

In [ ]:
# Setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"

device 

In [ ]:
# Count number of devices

torch.cuda.device_count()

In [ ]:
# Device Agnostic Code

In [ ]:
tensoor = torch.tensor([1,2,3], device ="cpu")
tensor_on_gpu = tensoor.to(device)

#if tensor is on GPU cant transform to numpy